### ISSUE TITLE
llama.cpp commit hash under "help" is stuck on version of toolbox

### ISSUE THREAD

**Issue by ThiloteE** [3Simplex/Llama.Cpp-Toolbox#3]
I have updated multiple times.
![image](https://github.com/user-attachments/assets/13f36d78-9315-4fa3-9234-a531286f26c0)
It's stuck on version `923b0fb`.

![image](https://github.com/user-attachments/assets/70b40220-0a9d-48b6-9096-894557b85f37)

I think I know what happens: In the UI it says it is a hash of llama.cpp, but actually, it is the hash of the [toolbox](https://github.com/3Simplex/Llama.Cpp-Toolbox/commit/923b0fb26b357dc23d4c83533b65e16458e0a61b).

Would be nice to have both hashes in there. The current implementation simply needs renaming, then we know the name of the toolbox version. For llama.cpp it something would need to be changed.

**Comment by 3Simplex** [comment]
The mistake has been resolved, thanks for the assist. I'll have to add the other info when I decide how to modify the form. This was just a placeholder.
